export const actionTypes = {
  TICK: 'TICK',
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  RESET: 'RESET',
  ADDNUM: 'ADDNUM',
  ADD_TASK: 'ADD_TASK',
  REQUESTED_CLUBS: 'REQUESTED_CLUBS',
  REQUEST: 'REQUEST',
  REQUESTED_GAMES: 'REQUESTED_GAMES',
  REQUEST_FILTER_TOGGLE: 'REQUEST_FILTER_TOGGLE',
};
